openapi: 3.0.0
tags:
  - name: User
    description: 'Get User profile, login'
info:
  title: doc2
  version: '1.0'
  contact:
    name: Hugo Cheung
    email: hugocheung@Instajs.com
  description: Api documentation mainly for mobile client
servers:
  - url: 'http://sallyapi.ijs.network:8080/api'
paths:
  /user/login:
    post:
      summary: ''
      operationId: post-user-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                    description: 'login token for subsequent api calls, being inserted in the request header'
              examples:
                example-1:
                  value:
                    success: true
                    token: 2c3f70d0-4c42-4346-90a8-7d5849a2a34a
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
                device_id:
                  type: string
            examples:
              example-1:
                value:
                  user_name: invalid user name
                  password: invalid password
                  device_id: '123123'
      description: User login (mobile/ web)
      tags:
        - User
  /user/profile:
    get:
      summary: Your GET endpoint
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      staff_id:
                        type: string
                      full_name:
                        type: string
                      email:
                        type: string
                      tel:
                        type: string
                      gender:
                        type: string
                      direct_line:
                        type: string
                      avatar_url:
                        type: string
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      staff_id: '123456'
                      full_name: null
                      email: hugocheung@instajs.com
                      tel: '66667777'
                      gender: M
                      direct_line: '22223334'
                      avatar_url: null
      operationId: get-user-profile
      requestBody:
        content:
          application/json:
            schema: {}
        description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: login token
          required: true
      description: "Get user's profile info"
    patch:
      summary: ''
      operationId: patch-user-profile
      responses:
        '200':
          description: OK
      description: "Edit user's profile"
      tags:
        - User
components:
  schemas: {}
